### ISSUE TITLE
Error: libBackgroundTransfer.a are required to have universal iOS libraries

### ISSUE THREAD

**Issue by Plozzer** [ncreated/BackgroundTransfer-ANE#1]
Hi,

I tried to install this ane on IPAD throw flash professional and i received this error:

Error:  META-INF/ANE/iPhone-ARM libBackgroundTransfer.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

I think the .ane in the zip file does not work with latest ios versions.

**Comment by ncreated** [comment]
Thanks for reporting. Indeed, `lipo` revealed that ANE was missing arm64 binary:

```
lipo -info libBackgroundTransferANE.a 
Non-fat file: META-INF/ANE/iPhone-ARM/libBackgroundTransferANE.a is architecture: armv7
```

I did the fix and it should be correct. Since I don't use Flash IDE, please download and test the latest ANE from `develop`:

https://github.com/ncreated/BackgroundTransfer-ANE/tree/develop

and let me know if the problem gone.

**Comment by Plozzer** [comment]
Thank you,
works great, the error disappeared!
